mappings:
  - name: patient_demographics
    doc_type: pb_impowr_demographics
    type: aggregator
    root: pb_impowr_demographics
    props:
      - name: submitter_id
      - name: project_id
      - name: impdgenid
      - name: impdsex
      - name: impd_race
      - name: impd_ethnic
      - name: imp_relat
      - name: imp_age
    parent_props:
      - path: pb_demographics.patient_baselines.patients[patient_id:submitter_id]

  - name: patient_ptsd
    doc_type: pb_primarycare_ptsd_screening
    type: aggregator
    root: pb_primarycare_ptsd_screening
    props:
      - name: submitter_id
      - name: project_id
      - name: pcptsd5score
      - name: pcptsddetachyn
      - name: pcptsdguiltyn
      - name: pcptsdtraumayn
    parent_props:
      - path: pb_ptsds.patient_baselines.patients[patient_id:submitter_id]


  - name: patient_od5
    doc_type: pb_impowr_overdose_screening
    type: aggregator
    root: pb_impowr_overdose_screening
    props:
      - name: submitter_id
      - name: project_id
      - name: opioidodnumtimes
      - name: opioidodnarcan
    parent_props:
      - path: pb_substance_uses.patient_baselines.patients[patient_id:submitter_id]


  - name: patients_nested
    doc_type: patient
    type: aggregator
    root: patient
    props:
      - name: submitter_id
      - name: project_id
    nested_props:
      - name: demographics
        path: patient_baselines.pb_demographics.pb_impowr_demographics
        props:
          - name: impdgenid
          - name: impdsex
          - name: impd_race
          - name: impd_ethnic
          - name: imp_relat
          - name: imp_age
      - name: substance_use
        path: patient_baselines.pb_substance_uses.pb_impowr_overdose_screenings
        props:
          - name: opioidodnumtimes
          - name: opioidodnarcan
      - name: depression
        path: patient_baselines.pb_depressions.pb_promis_depressions
        props:
          - name: promisdep4atotalscore
          - name: promisdprssdfeelpst7dyscl
          - name: promiswrthlsfeelpst7dyscl