apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.{{ .Values.ARGOCD_PREFIX }}-gcp-pubsub-indexing.{{ .Release.Namespace }}
spec:
  dlp:
    settings: []
    status: true
  egress:
  - action: allow
    applications:
    - DNS
    name: nv.kube-dns.kube-system-egress-10
    ports: any
    priority: 0
    selector:
      comment: ""
      criteria:
      - key: service
        op: =
        value: kube-dns.kube-system
      - key: domain
        op: =
        value: kube-system
      name: nv.kube-dns.kube-system
      original_name: ""
  - action: allow
    applications:
    - SSL
    name: external-egress-11
    ports: any
    priority: 0
    selector:
      comment: ""
      criteria: []
      name: external
      original_name: ""
  file: []
  ingress: []
  process:
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  - action: allow
    allow_update: false
    name: server
    path: /app/server
  - action: allow
    allow_update: false
    name: sh
    path: /bin/dash
  process_profile:
    baseline: zero-drift
  target:
    policymode: {{ .Values.POLICY_MODE }}
    selector:
      comment: ""
      criteria:
      - key: service
        op: =
        value: {{ .Values.ARGOCD_PREFIX }}-gcp-pubsub-indexing.{{ .Release.Namespace }}
      - key: domain
        op: =
        value: {{ .Release.Namespace }}
      name: nv.{{ .Values.ARGOCD_PREFIX }}-gcp-pubsub-indexing.{{ .Release.Namespace }}
      original_name: ""
  waf:
    settings: []
    status: true