global:
  # -- (bool) Whether public datasets are enabled.
  publicDataSets: false
  # -- (string) Access level for tiers.
  tierAccessLevel: private
  dictionaryUrl: https://impowrgen3.wakehealth.edu/dictionary_schema
  aws:
    enabled: false
  hostname: impowrgen3.wakehealth.edu
  dev: true
  postgres: 
    dev: true
    dbCreate: true
    master:
      host:
      username: postgres
      password:
      port: "5432"
postgresql:
  primary:
    persistence:
      enabled: true

aws-es-proxy:
  enabled: false
  esEndpoint: http://elasticsearch:9200

metadata:
  GEN3_DEBUG: "True"
  esEndpoint: http://elasticsearch:9200
  useAggMds: "False"
  aggMdsNamespace: gen3

guppy:
  dbRestore: false
  enabled: true
  esEndpoint: http://elasticsearch:9200
  # Configmap
  indices:
  - index: dev_file_0
    type: file
  - index: dev_etl_0
    type: study
  - index: patient_demographics_0
    type: pb_impowr_demographics
  - index: patient_ptsd_0
    type: pb_primarycare_ptsd_screening
  - index: patient_od5_0
    type: pb_impowr_overdose_screening
  - index: patients_nested_0
    type: patient
  configIndex: gen3-dev-config

sheepdog: 
  authNamespace: gen3 
  dictionaryUrl: https://impowrgen3.wakehealth.edu/dictionary_schema  
  indexdUrl: http://indexd-service  
  fenceUrl: http://fence-service  
  arboristUrl: http://arborist-service  
  INDEXD_USER: honey  
  INDEXD_PASS: mustard

portal:
  dataUploadBucket: wf-gen3-private-bucket
  image:
    repository: quay.io/cdis/data-portal
    tag: "2023.04"

revproxy:
  ingress:
    annotations:
      acme.cert-manager.io/http01-edit-in-place: 'true'
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/issue-temporary-certificate: 'true'
    tls:
    - hosts:
        - impowrgen3.wakehealth.edu
      secretName: impowrgen3-wakehealth-edu-tls

peregrine:
  arboristUrl: http://arborist-service
#   env:
#     CONF_HOSTNAME: impowrgen3.wakehealth.edu

indexd:
  db-secret: indexd-dbcreds
  enabled: true
  env:
  - name: GEN3_DEBUG
    value: "True"

gcp-pubsub-indexing:
  enabled: true
  GCP_PROJECT_ID: "wf-gen3"
  GCP_SUBSCRIPTION_ID: "file_uploaded-sub"
  INDEXD_USERNAME: "honey"
  INDEXD_PASSWORD: "mustard"
  HOSTNAME: "https://impowrgen3.wakehealth.edu"

tube:
  enabled: true

spark:
  enabled: true

fence:
  image:
    repository: quay.io/cdis/fence
    tag: "2023.04"
  serviceAccount:
    # Specifies whether a service account should be created
    # -- (bool) Whether to create a service account
    create: true
    # Annotations to add to the service account
    annotations: {}
      # -- (string) The Amazon Resource Name (ARN) of the role to associate with the service account
      # eks.amazonaws.com/role-arn:
  enabled: true
  db-secret: fence-dbcreds



requestor:
  enabled: false
  image:
    repository: quay.io/cdis/requestor
    tag: master
  
# common:
#   db-secret: "{{ $.Chart.Name }}-dbcreds"

# arborist:
#   db-secret: arborist-dbcreds

# audit:
#   db-secret: audit-dbcreds

tags:
  dev: true

ambassador:
  enabled: true
  labels:
    app: ambassador
  podLabels:
    app: ambassador
  selectorLabels:
    app: ambassador
