apiVersion: v1
kind: Secret
metadata:
  name: metadata-g3auto
stringData:
  {{- $randomPass := printf "%s%s" "gateway:" (randAlphaNum 32)  }}
  base64Authz.txt: {{  $randomPass | b64enc | quote  }}
  dbcreds.json: |
    {
      "db_host": "{{ include "gen3.service-postgres" (dict "key" "host" "service" $.Chart.Name "context" $) }}",
      "db_username": "{{include "gen3.service-postgres" (dict "key" "username" "service" $.Chart.Name "context" $) }}",
      "db_password": "{{include "gen3.service-postgres" (dict "key" "password" "service" $.Chart.Name "context" $) }}",
      "db_database": "{{ include "gen3.service-postgres" (dict "key" "database" "service" $.Chart.Name "context" $)}}"
    }
  metadata.env: | 
    DEBUG={{ .Values.debug}}
    DB_HOST={{ .Values.postgres.host  }}
    DB_USER={{ .Values.postgres.user }}
    DB_PASSWORD={{ include "metadata.postgres.password" .  }}
    DB_DATABASE={{ .Values.postgres.dbname  }}
    ADMIN_LOGINS={{ $randomPass  }}
