kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-pvc
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
